config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :employees do
    collection do
      post :import
    end
  end

  namespace :api do
    namespace :v1 do
      resources :employees do
        collection do
          post :import
        end
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
# frozen_string_literal: true

# Represents an employee in the company.
class Employee < ApplicationRecord
  validates :first_name, :last_name, :email, :contact_number, :date_of_birth, :date_of_hiring, presence: true
  validates :email, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  validates :contact_number, format: { with: /\A\d{10}\z/, message: 'should be 10 digits' }

  def age
    return nil unless date_of_birth.present?

    current_date = Date.today
    years_old(current_date)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_address
    "#{address}, #{city}, #{state}, #{pincode}"
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[address city contact_number date_of_birth date_of_hiring email first_name last_name
       pincode state]
  end

  private

  def years_old(current_date)
    age = current_date.year - date_of_birth.year
    age -= 1 if birthday_has_not_passed_yet?(current_date)
    age
  end

  def birthday_has_not_passed_yet?(current_date)
    current_date.month < date_of_birth.month ||
      (current_date.month == date_of_birth.month &&
      current_date.day < date_of_birth.day)
  end
end

app/controllers/api/v1/employees_controller.rb
# frozen_string_literal: true

# controller for employees
class Api::V1::EmployeesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_employee, only: %i[show update destroy]

  # GET /api/v1/employees
  def index
    @employees = Employee.all
    render json: @employees
  end

  # GET /api/v1/employees/:id
  def show
    render json: @employee
  end

  # POST /api/v1/employees
  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      render json: @employee, status: :created, message: 'Employee created successfully'
    else
      render json: @employee.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /api/v1/employees/:id
  def update
    if @employee.update(employee_params)
      render json: @employee, message: 'Employee updated successfully'
    else
      render json: @employee.errors, status: :unprocessable_entity
    end
  end

  # DELETE /api/v1/employees/:id
  def destroy
    @employee.destroy
    render json: { message: 'Employee deleted successfully' }
  end

  def import
    require 'csv'
    file = params[:file]
    if file
      CSV.foreach(file.path, headers: true) do |row|
        Employee.create(row.to_h)
      end
      render json: { message: 'Employee CSV imported successfully' }, status: :ok
    else
      render json: { message: 'No CSV uploaded, please upload a valid CSV file' }, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    render json: { message: e.message }
  end

  # Only allow a trusted parameter "white list" through.
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :contact_number, :address, :pincode, :city,
                                     :state, :date_of_birth, :date_of_hiring)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

# controller to for employees
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[show edit update destroy]

  # GET /employees
  def index
    @q = Employee.ransack(params[:q])
    @employees = @q.result(distinct: true)

    respond_to do |format|
      format.html
      format.csv { send_csv_data }
      format.xls { send_excel_data }
    end
  end

  # GET /employees/1
  def show; end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit; end

  # POST /employees
  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to @employee, notice: 'Employee was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /employees/1
  def update
    if @employee.update(employee_params)
      redirect_to @employee, notice: 'Employee was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /employees/1
  def destroy
    @employee.destroy
    redirect_to employees_url, notice: 'Employee was successfully destroyed.'
  end

  def import
    require 'csv'
    file = params[:file]

    CSV.foreach(file.path, headers: true) do |row|
      Employee.create(row.to_h)
    end

    redirect_to employees_path, notice: 'Employees imported successfully'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :contact_number, :address, :pincode,
                                     :city, :state, :date_of_birth, :date_of_hiring)
  end

  def send_csv_data
    csv_data = EmployeeCsvExportService.new(@employees).generate_csv
    send_data csv_data, filename: "employees-#{Date.today}.csv"
  end

  def send_excel_data
    xls_data = EmployeeExcelExportService.new(@employees).export_to_excel
    send_data xls_data, filename: "employees-#{Date.today}.xls"
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/api/v1/employees_helper.rb
module Api::V1::EmployeesHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

module EmployeesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true, html: { class: "row g-3" }) do |form| %>
  <div class="col-md-6">
    <%= form.label :first_name, class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :last_name, class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :contact_number, class: "form-label" %>
    <%= form.text_field :contact_number, class: "form-control" %>
  </div>

  <div class="col-12">
    <%= form.label :address, class: "form-label" %>
    <%= form.text_area :address, class: "form-control" %>
  </div>

  <div class="col-md-4">
    <%= form.label :pincode, class: "form-label" %>
    <%= form.text_field :pincode, class: "form-control" %>
  </div>

  <div class="col-md-4">
    <%= form.label :city, class: "form-label" %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="col-md-4">
    <%= form.label :state, class: "form-label" %>
    <%= form.text_field :state, class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :date_of_birth, class: "form-label" %>
    <%= form.date_field :date_of_birth, class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :date_of_hiring, class: "form-label" %>
    <%= form.date_field :date_of_hiring, class: "form-control" %>
  </div>

  <div class="col-12">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="container">
  <h1>Edit Employee</h1>
  <%= render 'form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<div class="container">
  <%= search_form_for @q, html: { class: "row g-3 mb-3" } do |f| %>
    <div class="col-md-3">
      <%= f.label :first_name_cont, "First Name", class: "form-label" %>
      <%= f.text_field :first_name_cont, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :last_name_cont, "Last Name", class: "form-label" %>
      <%= f.text_field :last_name_cont, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :email_cont, "Email", class: "form-label" %>
      <%= f.text_field :email_cont, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :contact_number_cont, "Contact Number", class: "form-label" %>
      <%= f.text_field :contact_number_cont, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :address_cont, "Address", class: "form-label" %>
      <%= f.text_field :address_cont, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :pincode_cont, "Pincode", class: "form-label" %>
      <%= f.text_field :pincode_cont, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :city_cont, "City", class: "form-label" %>
      <%= f.text_field :city_cont, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :state_cont, "State", class: "form-label" %>
      <%= f.text_field :state_cont, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :date_of_birth_gteq, "Date of Birth From", class: "form-label" %>
      <%= f.date_field :date_of_birth_gteq, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :date_of_birth_lteq, "Date of Birth To", class: "form-label" %>
      <%= f.date_field :date_of_birth_lteq, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :date_of_hiring_gteq, "Date of Hiring From", class: "form-label" %>
      <%= f.date_field :date_of_hiring_gteq, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :date_of_hiring_lteq, "Date of Hiring To", class: "form-label" %>
      <%= f.date_field :date_of_hiring_lteq, class: "form-control" %>
    </div>

    <div class="col-12">
      <%= f.submit "Search", class: "btn btn-primary" %>
    </div>
  <% end %>


  <%= form_tag import_employees_path, multipart: true, class: "mb-3 row g-3" do %>
    <div class="col-md-8">
      <div class="input-group">
        <%= file_field_tag :file, class: "form-control", id: "inputGroupFile", aria_describedby: "inputGroupFileAddon" %>
        <label class="input-group-text" for="inputGroupFile">Choose file</label>
      </div>
    </div>
    <div class="col-md-4">
      <%= submit_tag "Import CSV", class: "btn btn-primary w-100" %>
    </div>
  <% end %>


  <h1 class="mt-5 mb-4">Employees List</h1>

  <% if @employees.any? %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Contact Number</th>
            <th scope="col">Date of hiring</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.full_name %></td>
              <td><%= employee.email %></td>
              <td><%= employee.contact_number %></td>
              <td><%= employee.date_of_hiring %></td>
              <td>
                <%= link_to 'Show', employee, class: 'btn btn-primary btn-sm mx-1' %>
                <%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-secondary btn-sm mx-1' %>
                <%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>No employees found.</p>
  <% end %>
    
</div>

app/views/employees/new.html.erb
<div class="container">
  <h1>New Employee</h1>
  <%= render 'form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<div class="container">
  <h1>Employee Details</h1>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Name: <%= @employee.full_name %></h5>
      <p class="card-text">Email: <%= @employee.email %></p>
      <p class="card-text">Contact Number: <%= @employee.contact_number %></p>
      <p class="card-text">Address: <%= @employee.full_address %></p>
      <p class="card-text">Date of Birth: <%= @employee.date_of_birth %></p>
      <p class="card-text">Date of Hiring: <%= @employee.date_of_hiring %></p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Welcome to ReactStaff!</h1>
<p>This is a dummy welcome text for the index page of ReactStaff.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactStaffBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>